name: "Tests"

on:
  push:
    branches:
      - "**"

env:
  go_version: "1.18"

jobs:
  uni-tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
          with:
            go-version: '^${{ env.go_version }}'
      - name: "Run unit tests"
        run: |
          go test -race -cover ./...
